Repository oclif/core, pull requests merged in 2023-11, with the labels that each got.

#845 feat: read extended tsconfigs
  package.json
  src/config/plugin.ts
  src/config/ts-node.ts
  src/errors/index.ts
  src/interfaces/plugin.ts
  src/interfaces/ts-config.ts
  src/module-loader.ts
  src/util/find-root.ts
  src/util/fs.ts
  test/config/config.flexible.test.ts
  test/config/config.test.ts
  test/config/ts-node.test.ts
  test/config/typescript.test.ts
  test/integration/esm-cjs.ts
  test/integration/plugins.e2e.ts
  test/integration/util.ts
  yarn.lock
Labels: enhancement

#857 fix: removes empty files attribute warning
  CHANGELOG.md
  package.json
  src/config/plugin.ts
Labels: cla:missing

#852 Enable themes
  package.json
  src/config/config.ts
  src/help/command.ts
  src/help/formatter.ts
  src/help/index.ts
  src/help/root.ts
  src/help/util.ts
  src/interfaces/config.ts
  src/util/util.ts
  test/config/config.test.ts
  test/help/format-command-with-options.test.ts
  test/help/format-command.test.ts
  test/help/util.test.ts
  test/util/util.test.ts
  yarn.lock
Labels: enhancement, cla:signed

#869 fix: change http to https in the lock file
  yarn.lock
Labels: cla:signed

#863 feat: improve flags indentation
  src/help/command.ts
  test/help/format-command-with-options.test.ts
  test/help/format-command.test.ts
Labels: cla:signed

#872 feat: indent all flags with no char below each other (#863)
  src/help/command.ts
  test/help/format-command-with-options.test.ts
  test/help/format-command.test.ts
Labels: cla:signed

#862 feat: enable themes (#852)
  CHANGELOG.md
  package.json
  src/cli-ux/index.ts
  src/cli-ux/theme.ts
  src/command.ts
  src/config/config.ts
  src/help/command.ts
  src/help/formatter.ts
  src/help/index.ts
  src/help/root.ts
  src/help/util.ts
  src/index.ts
  src/interfaces/config.ts
  src/interfaces/index.ts
  src/interfaces/theme.ts
  src/util/ids.ts
  test/cli-ux/theme.test.ts
  test/config/config.test.ts
  test/help/format-command-with-options.test.ts
  test/help/format-command.test.ts
  yarn.lock
Labels: cla:signed

#883 Fix this.log.bind(this)
  src/cli-ux/README.md
Labels: cla:missing

#887 fix: command not found on empty arg
  src/help/util.ts
  test/help/util.test.ts
Labels: cla:signed

#888 fix: command not found on empty arg (#887)
  src/help/util.ts
  test/help/util.test.ts
Labels: cla:signed

#880 feat: add 'multipleNonGreedy' flag option to assign only one value per multiple flag
  src/interfaces/parser.ts
  src/parser/parse.ts
  test/parser/parse.test.ts
Labels: cla:signed

#889 feat: add 'multipleNonGreedy' flag option to assign only one value per multiple flag (#880)
  src/interfaces/parser.ts
  src/parser/parse.ts
  test/parser/parse.test.ts
Labels: cla:signed
