Repository oclif/core, pull requests merged in 2024-06, with the labels that each got.

#1094 fix: get core meta version
  src/cache.ts
Labels: cla:missing

#1091 feat: added option to specify example flag value in docopts
  src/help/command.ts
  src/help/docopts.ts
  src/interfaces/parser.ts
  test/help/docopts.test.ts
  test/help/format-command.test.ts
Labels: enhancement, cla:signed

#1095 feat: added option to specify example flag value in docopts
  src/help/command.ts
  src/help/docopts.ts
  src/interfaces/parser.ts
  test/help/docopts.test.ts
  test/help/format-command.test.ts
Labels: cla:signed

#1108 fix: use lilconfig
  package.json
  src/util/read-pjson.ts
  yarn.lock
Labels: enhancement

#1112 fix: hide single command cli symbol on help output
  src/help/index.ts
Labels: cla:signed

#1124 fix: ignore cache when reading user pjson
  src/config/plugin-loader.ts
  src/util/fs.ts
Labels: enhancement
